### PR TITLE
Todays route displays all exercises for todays workout

### PR DESCRIPTION
**Pull request by brynschulha**
api/todays will select the workout with the date = date.today and then display all exercises for that workout

### CODE REVIEW

**Review by vvEii — COMMENTED** [review]
is that return an array of exercises?

**Review by vvEii — COMMENTED** [review]
the api should return an array of all workouts for today and each workout contains the workout id, workout name, and an array of exercises belongs to that workout.
For example: 

workouts: [
    {
      id: 1,
      name:‘workout one’,
      exercises: [{
        name:‘exercise one’,
        id: 1
      },
      {
        name:‘exercise two’,
        id: 2
      }]
    },
    {
      id: 2,
      name:‘workout two’,
      exercises: [{
        name:‘exercise one’,
        id: 1
      },
      {
        name:‘exercise two’,
        id: 2
      }]
    }
  ]

**Review by brynschulha — COMMENTED** [review]
api/todays is now returning the proper data structure

**Comment by vvEii** [comment]
That's works. Good job!

**Review by DyerMaker42 — APPROVED** [review]
Bless, ok so we just need to remember to define in model correct?

**Review by vvEii — APPROVED** [review]

**Pull request merged**
